# Generated by Django 5.2.5 on 2026-01-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock/ETF symbol', max_length=20)),
                ('sector', models.CharField(help_text='Market sector', max_length=100)),
                ('price_change_7d', models.FloatField(help_text='7-day price change %')),
                ('date', models.DateField(help_text='Data date')),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data',
                'ordering': ['-date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(help_text='Route description', max_length=200)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Disrupted', 'Disrupted'), ('Blocked', 'Blocked')], default='Normal', max_length=50)),
                ('freight_cost_index', models.FloatField(default=100.0, help_text='100 = baseline')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Route',
                'verbose_name_plural': 'Shipping Routes',
                'ordering': ['route_name'],
            },
        ),
        migrations.CreateModel(
            name='TariffData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_from', models.CharField(help_text='Exporting country', max_length=100)),
                ('country_to', models.CharField(help_text='Importing country', max_length=100)),
                ('sector', models.CharField(help_text='Industry sector', max_length=100)),
                ('tariff_rate', models.FloatField(help_text='Tariff percentage')),
                ('effective_date', models.DateField(help_text='When tariff takes effect')),
            ],
            options={
                'verbose_name': 'Tariff Data',
                'verbose_name_plural': 'Tariff Data',
                'ordering': ['-effective_date', '-tariff_rate'],
            },
        ),
    ]
